# Generated by Django 2.1.1 on 2019-01-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=0)),
                ('category_name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Entry_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_id', models.IntegerField(default=0)),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('Email_id', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Confirm_password', models.CharField(max_length=200)),
                ('Mobile_no', models.IntegerField(default=0)),
                ('Address', models.CharField(max_length=200)),
                ('Entry_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_id', models.IntegerField(default=0)),
                ('Product_id', models.IntegerField(default=0)),
                ('Product_name', models.CharField(max_length=200)),
                ('Model_no', models.IntegerField(default=0)),
                ('Colour', models.CharField(max_length=200)),
                ('Size', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=200)),
                ('Discount', models.CharField(max_length=200)),
                ('Shipping_charge', models.CharField(max_length=200)),
                ('Tax', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField(default=0)),
                ('Discription', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('Email_id', models.CharField(max_length=200)),
                ('Mobile_no', models.IntegerField(default=0)),
                ('Address', models.CharField(max_length=200)),
                ('Entry_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturer_id', models.IntegerField(default=0)),
                ('Manufacturer_name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Entry_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.IntegerField(default=0)),
                ('Product_name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('category_id', models.IntegerField(default=0)),
                ('Subcategory_id', models.IntegerField(default=0)),
                ('Manufacturer_id', models.IntegerField(default=0)),
                ('Dimension', models.IntegerField(default=0)),
                ('Model_no', models.IntegerField(default=0)),
                ('Price', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField(default=0)),
                ('Quantity_Max', models.IntegerField(default=0)),
                ('Quantity_Min', models.IntegerField(default=0)),
                ('Length', models.IntegerField(default=0)),
                ('Width', models.IntegerField(default=0)),
                ('Height', models.IntegerField(default=0)),
                ('Sort_order', models.IntegerField(default=0)),
                ('Colour', models.CharField(max_length=200)),
                ('Size', models.CharField(max_length=200)),
                ('Package', models.CharField(max_length=200)),
                ('Entry_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subcategory_id', models.IntegerField(default=0)),
                ('Subcategory_name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Entry_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
