# Generated by Django 2.1.1 on 2019-01-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyStock', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='SubCategorie',
            new_name='SubCategories',
        ),
    ]
