# Generated by Django 2.1.1 on 2019-01-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyStock', '0002_auto_20190119_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='Entry_date',
        ),
    ]
