# Generated by Django 2.1.1 on 2019-02-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyStock', '0003_remove_categories_entry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='Entry_date',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='Entry_date',
        ),
    ]
