# Generated by Django 2.1.1 on 2019-02-06 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyStock', '0004_auto_20190202_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Discount',
            new_name='Customer_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Entry_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Shipping_charge',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Tax',
        ),
    ]
